version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - exhaustive
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - paralleltest
    - predeclared
    - staticcheck
    - thelper
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - badCond
        - caseOrder
        - codegenComment
        - commentedOutCode
        - deprecatedComment
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - exitAfterDefer
        - flagDeref
        - flagName
        - nilValReturn
        - offBy1
        - sloppyReassign
        - weakCond
        - octalLiteral
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - rangeExprCopy
        - rangeValCopy
        - assignOp
        - boolExprSimplify
        - captLocal
        - commentFormatting
        - commentedOutImport
        - defaultCaseOrder
        - docStub
        - elseif
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - ifElseChain
        - methodExprCall
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - stringXbytes
        - switchTrue
        - typeAssertChain
        - typeSwitchVar
        - underef
        - unlabelStmt
        - unlambda
        - unslice
        - valSwap
        - wrapperFunc
        - yodaStyleExpr
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - typeUnparen
        - unnecessaryBlock
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    govet:
      enable:
        - fieldalignment
    wrapcheck:
      ignore-package-globs:
        - github.com/ossf/scorecard/v4/checks/fileparser
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ossf/scorecard)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
