runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 3.5
  disk_size_gb: 10

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  HOST: '0.0.0.0'
  VUE_APP_FRONTEND: 'https://openssf.uc.r.appspot.com'
